/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainProjectsRouteImport } from './routes/_main/projects'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainProjectsProjectSlugRouteImport } from './routes/_main/projects/$projectSlug'
import { Route as MainProjectsProjectSlugIndexRouteImport } from './routes/_main/projects/$projectSlug/index'
import { Route as MainProjectsProjectSlugBoardRouteImport } from './routes/_main/projects/$projectSlug/board'
import { Route as MainProjectsProjectSlugFeaturesRouteImport } from './routes/_main/projects/$projectSlug/features'
import { Route as MainProjectsProjectSlugTasksRouteImport } from './routes/_main/projects/$projectSlug/tasks'
import { Route as MainProjectsProjectSlugTasksIndexRouteImport } from './routes/_main/projects/$projectSlug/tasks/index'
import { Route as MainProjectsProjectSlugTasksTaskKeyRouteImport } from './routes/_main/projects/$projectSlug/tasks/$taskKey'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProjectsRoute,
} as any)
const MainProjectsProjectSlugRoute = MainProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => MainProjectsRoute,
} as any)
const MainProjectsProjectSlugIndexRoute =
  MainProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)
const MainProjectsProjectSlugBoardRoute =
  MainProjectsProjectSlugBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)
const MainProjectsProjectSlugFeaturesRoute =
  MainProjectsProjectSlugFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)
const MainProjectsProjectSlugTasksRoute =
  MainProjectsProjectSlugTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)
const MainProjectsProjectSlugTasksIndexRoute =
  MainProjectsProjectSlugTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainProjectsProjectSlugTasksRoute,
  } as any)
const MainProjectsProjectSlugTasksTaskKeyRoute =
  MainProjectsProjectSlugTasksTaskKeyRouteImport.update({
    id: '/$taskKey',
    path: '/$taskKey',
    getParentRoute: () => MainProjectsProjectSlugTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/projects': typeof MainProjectsRouteWithChildren
  '/settings': typeof MainSettingsRoute
  '/projects/$projectSlug': typeof MainProjectsProjectSlugRouteWithChildren
  '/projects/': typeof MainProjectsIndexRoute
  '/projects/$projectSlug/board': typeof MainProjectsProjectSlugBoardRoute
  '/projects/$projectSlug/features': typeof MainProjectsProjectSlugFeaturesRoute
  '/projects/$projectSlug/tasks': typeof MainProjectsProjectSlugTasksRouteWithChildren
  '/projects/$projectSlug/': typeof MainProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/tasks/$taskKey': typeof MainProjectsProjectSlugTasksTaskKeyRoute
  '/projects/$projectSlug/tasks/': typeof MainProjectsProjectSlugTasksIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof MainSettingsRoute
  '/': typeof MainIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/projects/$projectSlug/board': typeof MainProjectsProjectSlugBoardRoute
  '/projects/$projectSlug/features': typeof MainProjectsProjectSlugFeaturesRoute
  '/projects/$projectSlug': typeof MainProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/tasks/$taskKey': typeof MainProjectsProjectSlugTasksTaskKeyRoute
  '/projects/$projectSlug/tasks': typeof MainProjectsProjectSlugTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/projects': typeof MainProjectsRouteWithChildren
  '/_main/settings': typeof MainSettingsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/projects/$projectSlug': typeof MainProjectsProjectSlugRouteWithChildren
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/projects/$projectSlug/board': typeof MainProjectsProjectSlugBoardRoute
  '/_main/projects/$projectSlug/features': typeof MainProjectsProjectSlugFeaturesRoute
  '/_main/projects/$projectSlug/tasks': typeof MainProjectsProjectSlugTasksRouteWithChildren
  '/_main/projects/$projectSlug/': typeof MainProjectsProjectSlugIndexRoute
  '/_main/projects/$projectSlug/tasks/$taskKey': typeof MainProjectsProjectSlugTasksTaskKeyRoute
  '/_main/projects/$projectSlug/tasks/': typeof MainProjectsProjectSlugTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/settings'
    | '/projects/$projectSlug'
    | '/projects/'
    | '/projects/$projectSlug/board'
    | '/projects/$projectSlug/features'
    | '/projects/$projectSlug/tasks'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/tasks/$taskKey'
    | '/projects/$projectSlug/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/projects'
    | '/projects/$projectSlug/board'
    | '/projects/$projectSlug/features'
    | '/projects/$projectSlug'
    | '/projects/$projectSlug/tasks/$taskKey'
    | '/projects/$projectSlug/tasks'
  id:
    | '__root__'
    | '/_main'
    | '/_main/projects'
    | '/_main/settings'
    | '/_main/'
    | '/_main/projects/$projectSlug'
    | '/_main/projects/'
    | '/_main/projects/$projectSlug/board'
    | '/_main/projects/$projectSlug/features'
    | '/_main/projects/$projectSlug/tasks'
    | '/_main/projects/$projectSlug/'
    | '/_main/projects/$projectSlug/tasks/$taskKey'
    | '/_main/projects/$projectSlug/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects': {
      id: '/_main/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainProjectsRoute
    }
    '/_main/projects/$projectSlug': {
      id: '/_main/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof MainProjectsProjectSlugRouteImport
      parentRoute: typeof MainProjectsRoute
    }
    '/_main/projects/$projectSlug/': {
      id: '/_main/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof MainProjectsProjectSlugIndexRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
    '/_main/projects/$projectSlug/board': {
      id: '/_main/projects/$projectSlug/board'
      path: '/board'
      fullPath: '/projects/$projectSlug/board'
      preLoaderRoute: typeof MainProjectsProjectSlugBoardRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
    '/_main/projects/$projectSlug/features': {
      id: '/_main/projects/$projectSlug/features'
      path: '/features'
      fullPath: '/projects/$projectSlug/features'
      preLoaderRoute: typeof MainProjectsProjectSlugFeaturesRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
    '/_main/projects/$projectSlug/tasks': {
      id: '/_main/projects/$projectSlug/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectSlug/tasks'
      preLoaderRoute: typeof MainProjectsProjectSlugTasksRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
    '/_main/projects/$projectSlug/tasks/': {
      id: '/_main/projects/$projectSlug/tasks/'
      path: '/'
      fullPath: '/projects/$projectSlug/tasks/'
      preLoaderRoute: typeof MainProjectsProjectSlugTasksIndexRouteImport
      parentRoute: typeof MainProjectsProjectSlugTasksRoute
    }
    '/_main/projects/$projectSlug/tasks/$taskKey': {
      id: '/_main/projects/$projectSlug/tasks/$taskKey'
      path: '/$taskKey'
      fullPath: '/projects/$projectSlug/tasks/$taskKey'
      preLoaderRoute: typeof MainProjectsProjectSlugTasksTaskKeyRouteImport
      parentRoute: typeof MainProjectsProjectSlugTasksRoute
    }
  }
}

interface MainProjectsProjectSlugTasksRouteChildren {
  MainProjectsProjectSlugTasksTaskKeyRoute: typeof MainProjectsProjectSlugTasksTaskKeyRoute
  MainProjectsProjectSlugTasksIndexRoute: typeof MainProjectsProjectSlugTasksIndexRoute
}

const MainProjectsProjectSlugTasksRouteChildren: MainProjectsProjectSlugTasksRouteChildren =
  {
    MainProjectsProjectSlugTasksTaskKeyRoute:
      MainProjectsProjectSlugTasksTaskKeyRoute,
    MainProjectsProjectSlugTasksIndexRoute:
      MainProjectsProjectSlugTasksIndexRoute,
  }

const MainProjectsProjectSlugTasksRouteWithChildren =
  MainProjectsProjectSlugTasksRoute._addFileChildren(
    MainProjectsProjectSlugTasksRouteChildren,
  )

interface MainProjectsProjectSlugRouteChildren {
  MainProjectsProjectSlugBoardRoute: typeof MainProjectsProjectSlugBoardRoute
  MainProjectsProjectSlugFeaturesRoute: typeof MainProjectsProjectSlugFeaturesRoute
  MainProjectsProjectSlugTasksRoute: typeof MainProjectsProjectSlugTasksRouteWithChildren
  MainProjectsProjectSlugIndexRoute: typeof MainProjectsProjectSlugIndexRoute
}

const MainProjectsProjectSlugRouteChildren: MainProjectsProjectSlugRouteChildren =
  {
    MainProjectsProjectSlugBoardRoute: MainProjectsProjectSlugBoardRoute,
    MainProjectsProjectSlugFeaturesRoute: MainProjectsProjectSlugFeaturesRoute,
    MainProjectsProjectSlugTasksRoute:
      MainProjectsProjectSlugTasksRouteWithChildren,
    MainProjectsProjectSlugIndexRoute: MainProjectsProjectSlugIndexRoute,
  }

const MainProjectsProjectSlugRouteWithChildren =
  MainProjectsProjectSlugRoute._addFileChildren(
    MainProjectsProjectSlugRouteChildren,
  )

interface MainProjectsRouteChildren {
  MainProjectsProjectSlugRoute: typeof MainProjectsProjectSlugRouteWithChildren
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
}

const MainProjectsRouteChildren: MainProjectsRouteChildren = {
  MainProjectsProjectSlugRoute: MainProjectsProjectSlugRouteWithChildren,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
}

const MainProjectsRouteWithChildren = MainProjectsRoute._addFileChildren(
  MainProjectsRouteChildren,
)

interface MainRouteChildren {
  MainProjectsRoute: typeof MainProjectsRouteWithChildren
  MainSettingsRoute: typeof MainSettingsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainProjectsRoute: MainProjectsRouteWithChildren,
  MainSettingsRoute: MainSettingsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
