/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainProjectsProjectSlugRouteImport } from './routes/_main/projects/$projectSlug'
import { Route as MainProjectsProjectSlugIndexRouteImport } from './routes/_main/projects/$projectSlug/index'
import { Route as MainProjectsProjectSlugBoardRouteImport } from './routes/_main/projects/$projectSlug/board'
import { Route as MainProjectsProjectSlugFeaturesRouteImport } from './routes/_main/projects/$projectSlug/features'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsProjectSlugRoute = MainProjectsProjectSlugRouteImport.update({
  id: '/projects/$projectSlug',
  path: '/projects/$projectSlug',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsProjectSlugIndexRoute =
  MainProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)
const MainProjectsProjectSlugBoardRoute =
  MainProjectsProjectSlugBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)
const MainProjectsProjectSlugFeaturesRoute =
  MainProjectsProjectSlugFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => MainProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/settings': typeof MainSettingsRoute
  '/projects/$projectSlug': typeof MainProjectsProjectSlugRouteWithChildren
  '/projects/': typeof MainProjectsIndexRoute
  '/projects/$projectSlug/board': typeof MainProjectsProjectSlugBoardRoute
  '/projects/$projectSlug/features': typeof MainProjectsProjectSlugFeaturesRoute
  '/projects/$projectSlug/': typeof MainProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof MainSettingsRoute
  '/': typeof MainIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/projects/$projectSlug/board': typeof MainProjectsProjectSlugBoardRoute
  '/projects/$projectSlug/features': typeof MainProjectsProjectSlugFeaturesRoute
  '/projects/$projectSlug': typeof MainProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/settings': typeof MainSettingsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/projects/$projectSlug': typeof MainProjectsProjectSlugRouteWithChildren
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/projects/$projectSlug/board': typeof MainProjectsProjectSlugBoardRoute
  '/_main/projects/$projectSlug/features': typeof MainProjectsProjectSlugFeaturesRoute
  '/_main/projects/$projectSlug/': typeof MainProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/projects/$projectSlug'
    | '/projects/'
    | '/projects/$projectSlug/board'
    | '/projects/$projectSlug/features'
    | '/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/projects'
    | '/projects/$projectSlug/board'
    | '/projects/$projectSlug/features'
    | '/projects/$projectSlug'
  id:
    | '__root__'
    | '/_main'
    | '/_main/settings'
    | '/_main/'
    | '/_main/projects/$projectSlug'
    | '/_main/projects/'
    | '/_main/projects/$projectSlug/board'
    | '/_main/projects/$projectSlug/features'
    | '/_main/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$projectSlug': {
      id: '/_main/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof MainProjectsProjectSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$projectSlug/': {
      id: '/_main/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof MainProjectsProjectSlugIndexRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
    '/_main/projects/$projectSlug/board': {
      id: '/_main/projects/$projectSlug/board'
      path: '/board'
      fullPath: '/projects/$projectSlug/board'
      preLoaderRoute: typeof MainProjectsProjectSlugBoardRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
    '/_main/projects/$projectSlug/features': {
      id: '/_main/projects/$projectSlug/features'
      path: '/features'
      fullPath: '/projects/$projectSlug/features'
      preLoaderRoute: typeof MainProjectsProjectSlugFeaturesRouteImport
      parentRoute: typeof MainProjectsProjectSlugRoute
    }
  }
}

interface MainProjectsProjectSlugRouteChildren {
  MainProjectsProjectSlugBoardRoute: typeof MainProjectsProjectSlugBoardRoute
  MainProjectsProjectSlugFeaturesRoute: typeof MainProjectsProjectSlugFeaturesRoute
  MainProjectsProjectSlugIndexRoute: typeof MainProjectsProjectSlugIndexRoute
}

const MainProjectsProjectSlugRouteChildren: MainProjectsProjectSlugRouteChildren =
  {
    MainProjectsProjectSlugBoardRoute: MainProjectsProjectSlugBoardRoute,
    MainProjectsProjectSlugFeaturesRoute: MainProjectsProjectSlugFeaturesRoute,
    MainProjectsProjectSlugIndexRoute: MainProjectsProjectSlugIndexRoute,
  }

const MainProjectsProjectSlugRouteWithChildren =
  MainProjectsProjectSlugRoute._addFileChildren(
    MainProjectsProjectSlugRouteChildren,
  )

interface MainRouteChildren {
  MainSettingsRoute: typeof MainSettingsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainProjectsProjectSlugRoute: typeof MainProjectsProjectSlugRouteWithChildren
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSettingsRoute: MainSettingsRoute,
  MainIndexRoute: MainIndexRoute,
  MainProjectsProjectSlugRoute: MainProjectsProjectSlugRouteWithChildren,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
